version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-35
      - build-36
      - build-37
      - build-38
      - lint
      - typecheck

jobs:
  build-35: &build-template
    docker:
      - image: circleci/python:3.5

    steps:
      - checkout
      - run: python setup.py test

  build-36:
    <<: *build-template
    docker:
      - image: circleci/python:3.6

  build-37:
    <<: *build-template
    docker:
      - image: circleci/python:3.7

  build-38:
    <<: *build-template
    docker:
      - image: circleci/python:3.8

  lint:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            venv/bin/pip install -r script/linting/requirements.txt
      - run:
          name: Lint
          command: script/linting/lint
          environment:
            FLAKE8: venv/bin/flake8

  typecheck:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            venv/bin/pip install -r script/typing/requirements.txt
      - run:
          name: Typecheck
          command: script/typing/check
          environment:
            MYPY: venv/bin/mypy
